# _config.yml

title: "Rishika Agarwal"
name: "Rishika Agarwal"
description: "Postgraduate in Business Analytics | Data-Driven Solutions | University of Warwick"
url: "https://rishikaagarwal2025.github.io"
baseurl: ""

# Author Info
author:
  name: "Rishika Agarwal"
  email: "rishikaagarwal544@gmail.com"
  location: "United Kingdom"
  avatar: "/assets/images/profile.jpeg"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/rishika-agarwal-uk"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/RishikaAgarwal2025"

# Navigation Tabs
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /About-Me/
  - title: "Academic Projects"
    url: /Projects/
  - title: "Dissertation"
    url: /Dissertation/
  - title: "Teaching"
    url: /Teaching/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /Contact/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# Layout Defaults
defaults:
  - scope:
      path: "_pages"
    values:
      layout: default
      permalink: /:name/

# Markdown
markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
