title: "Rishika Agarwal"
subtitle: "Business Analytics Portfolio"
description: "A portfolio website showcasing academic projects, teaching, CV, and contact information."
baseurl: "" 
url: "https://rishikaagarwal2025.github.io"
repository: "RishikaAgarwal2025/RishikaAgarwal2025.github.io"

author:
  name: "Rishika Agarwal"
  avatar: "/assets/images/profile.jpg"
  bio: "MSc Business Analytics | Python, SQL, Tableau | Business Analyst Enthusiast"
  location: "UK / India"
  email: "rishikaagarwal544@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:rishikaagarwal544@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/RishikaAgarwal2025/Business-Analysis-Portfolio"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/rishika-agarwal-uk"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about-me/
  - title: "Academic Projects"
    url: /projects/
  - title: "Dissertation"
    url: /dissertation/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/RishikaAgarwal2025"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/rishika-agarwal-uk"

atom_feed:
  hide: true

permalink: /:title/

include:
  - pages

markdown: kramdown
highlighter: rouge

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
