# _config.yml

# Site settings
title: "Rishika Agarwal"
name: "Rishika Agarwal"
description: "Postgraduate in Business Analytics | Data-Driven Solutions | University of Warwick"
url: "https://rishikaagarwal2025.github.io"
baseurl: ""  # Keep empty for user.github.io repository

# Theme
theme: jekyll-theme-minimal

# Author Info
author:
  name: "Rishika Agarwal"
  email: "rishikaagarwal544@gmail.com"
  location: "United Kingdom"
  avatar: "/assets/images/profile.jpeg"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/rishika-agarwal-uk"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/RishikaAgarwal2025"

# Navigation Tabs
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about/
  - title: "Academic Projects"
    url: /projects/
  - title: "Dissertation"
    url: /dissertation/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

# Collections (optional, if using custom subpages)
collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  projects:
    output: true
    permalink: /projects/:path/
  dissertation:
    output: true
    permalink: /dissertation/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# Defaults for layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: teaching
    values:
      layout: page
  - scope:
      path: ""
      type: projects
    values:
      layout: page
  - scope:
      path: ""
      type: dissertation
    values:
      layout: page

# Markdown & Permalink settings
markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Files to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# SEO Social Links
social:
  type: "Person"
  name: "Rishika Agarwal"
  links:
    - "https://github.com/RishikaAgarwal2025"
    - "https://www.linkedin.com/in/r
