# _config.yml

# Site settings
title: "Rishika Agarwal"
name: "Rishika Agarwal"
description: "Postgraduate in Business Analytics | Data-Driven Solutions | University of Warwick"
url: "https://rishikaagarwal2025.github.io" # GitHub Pages URL
baseurl: "" # Keep empty if using username.github.io
repository: "RishikaAgarwal2025/RishikaAgarwal2025.github.io"
locale: "en-US"
site_theme: "minimal"

# Author settings
author:
  name: "Rishika Agarwal"
  avatar: "/assets/images/profile.jpeg"
  email: "rishikaagarwal544@gmail.com"
  location: "United Kingdom"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/rishika-agarwal-uk"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/RishikaAgarwal2025"

# Navigation (will be used in header if supported by theme)
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Academic Projects"
    url: /projects/
  - title: "Dissertation"
    url: /dissertation/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  dissertation:
    output: true
    permalink: /:collection/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: dissertation
    values:
      layout: single
      author_profile: true

# Markdown and Permalink settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Exclusions
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# Sitemap
sitemap:
  exclude:
    - /assets/
    - /images/

# Analytics (disabled, optional)
analytics:
  provider: false

# Comments (disabled)
comments:
  provider: false

# Social metadata (optional)
social:
  type: "Person"
  name: "Rishika Agarwal"
  links:
    - "https://github.com/RishikaAgarwal2025"
    - "https://www.linkedin.com/in/rishika-agarwal-uk"
